import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const page = readFileSync(path.resolve(process.cwd(), 'src/pages/JobDiscoveryPage.tsx'), 'utf8')
const analysis = readFileSync(path.resolve(process.cwd(), 'src/pages/JobAnalysisPage.tsx'), 'utf8')
const layout = readFileSync(path.resolve(process.cwd(), 'src/components/layout/AppLayout.tsx'), 'utf8')
const client = readFileSync(path.resolve(process.cwd(), 'src/lib/ai/client.ts'), 'utf8')

describe('live jobs contracts', () => {
  it('searches through the backend catalog and labels results as Live', () => {
    expect(layout).toMatch(/Live Jobs/)
    expect(page).toMatch(/listLiveJobsRequest/)
    expect(page).toMatch(/Search live jobs/)
    expect(page).toMatch(/● Live/)
    expect(page).toMatch(/Job Opportunities API/)
    expect(page).toMatch(/Apply Now/)
    expect(page).toMatch(/getLiveJobRequest/)
    expect(page).toMatch(/Job data provided by/)
    expect(page).not.toMatch(/Live Demo Provider/)
    expect(page).not.toMatch(/Source: \{providerLabel/)
    expect(page).not.toMatch(/createSampleWorkspace|SAMPLE_RESUME/)
    expect(page).not.toMatch(/api\.jobopportunitiesapi\.org/)
    expect(client).toMatch(/fetch\(apiUrl\(`\/api\/jobs\?/)
    expect(client).toMatch(/method: 'POST'/)
  })

  it('shows resume match scores and sorts without opening analysis first', () => {
    expect(page).toMatch(/Resume Match/)
    expect(page).toMatch(/Matched/)
    expect(page).toMatch(/Missing/)
    expect(page).toMatch(/Match Score: High to Low/)
    expect(page).toMatch(/Most Recent/)
    expect(page).toMatch(/Relevance/)
    expect(page).toMatch(/sortDiscoveredJobs/)
    expect(page).toMatch(/resumeText: resume\?\.parsedText/)
    expect(page).not.toMatch(/Analyze Job/)
  })

  it('opens Apply Now on the employer URL and Review & Apply in-page', () => {
    expect(page).toMatch(/Apply Now/)
    expect(page).toMatch(/Review & Apply/)
    expect(page).toMatch(/Save Job/)
    expect(page).toMatch(/target="_blank"/)
    expect(page).toMatch(/employerApplyHref/)
    expect(page).toMatch(/setReviewing/)
    expect(page).toMatch(/previewLiveJobRequest/)
    expect(page).toMatch(/Current Resume Match/)
    expect(page).toMatch(/Tailored Resume Match/)
    expect(page).toMatch(/Use Current Resume/)
    expect(page).toMatch(/Tailor Resume/)
    expect(page).toMatch(/View Details/)
    expect(page).toMatch(/saveDiscoveredJob/)
    expect(page).not.toMatch(/submit application/i)
    expect(page).not.toMatch(/function goAnalyze/)
    expect(page).toMatch(/function onTailorResume/)
  })

  it('adds a C2C filter and compact Auto Apply controls without replacing Apply Now', () => {
    expect(page).toMatch(/Job type/)
    expect(page).toMatch(/C2C/)
    expect(page).toMatch(/Auto Apply/)
    expect(page).toMatch(/Start Auto Apply/)
    expect(page).toMatch(/Minimum match/)
    expect(page).toMatch(/Number of jobs/)
    expect(page).toMatch(/Auto-update resume/)
    expect(page).toMatch(/startAutoApplyRequest/)
    expect(page).toMatch(/jobType/)
    expect(client).toMatch(/\/api\/jobs\/auto-apply\/start/)
    expect(page).toMatch(/Apply Now/)
    expect(page).not.toMatch(/submit application/i)
  })

  it('persists Auto Apply jobs into Applications after Apply, Review, or Submit', () => {
    expect(page).toMatch(/syncAutoApplyApplication/)
    expect(page).toMatch(/persistQueueApplication/)
    expect(page).toMatch(/Application could not be saved/)
    expect(page).toMatch(/applicationStatus === 'automation_blocked'/)
    expect(page).toMatch(/await persistQueueApplication\(prepared\)/)
    expect(page).toMatch(/await persistQueueApplication\(submitted\)/)
    expect(page).toMatch(/submitted\.applicationStatus === 'submitted'/)
    expect(page).toMatch(/await persistQueueApplication\(item\)/)
    expect(page).toMatch(/handshakeExtensionSession/)
    expect(page).toMatch(/requestExtensionQueueProcessing/)
    expect(page).toMatch(/persistError instanceof Error \? persistError\.message : 'Application could not be saved\.'/)
  })

  it('pre-fills Job Analysis from a live job when the user explicitly tailors', () => {
    expect(analysis).toMatch(/liveJob/)
    expect(analysis).toMatch(/jobId: liveJobId/)
    expect(analysis).toMatch(/title: fieldsRef.current.title/)
    expect(analysis).toMatch(/Job title/)
    expect(analysis).toMatch(/provider: liveMeta\?\.provider/)
    expect(page).toMatch(/state: \{ liveJob: hydrated \}/)
  })
})
